---
- name: Is nginx already installed
  shell: "which nginx"
  register: is_nginx
  ignore_errors: yes

- name: Install nginx
  yum:
    name=nginx
    state=present
  when: is_nginx.rc != 0

- name: Copy nginx base configuration
  template:
    src=nginx.conf
    dest=/etc/nginx/
  notify: restart nginx

- name: Copy nginx configuration
  template:
    src=your-app.conf
    dest=/etc/nginx/conf.d/your-app.conf
  notify: restart nginx

- name: Insert firewalld rule for http & https
  firewalld:
    port={{ item }}/tcp
    permanent=true
    state=enabled
    immediate=yes
  ignore_errors: yes
  with_items:
    - "{{ port.http }}"
    - "{{ port.https }}"

- name: Delete unnecessary files
  file:
    path={{ item }}
    state=absent
  with_items:
    - /etc/nginx/koi-utf
    - /etc/nginx/koi-win
    - /etc/nginx/win-utf
    - /etc/nginx/conf.d/default.conf

- name: http service state
  service:
    name=nginx
    state=started
    enabled=yes